import { Component, OnInit } from '@angular/core';
import { FormGroup,FormControl,Validators } from '@angular/forms';
import { NCMCodeI } from './ncmCode.interface';
import { CodigoSI } from './codigoClasificacionStore.interface';
import { ClasificacionI } from './clasificacion.interface';
import { AndService } from 'src/app/services/api/and.service';

@Component({
  selector: 'app-agregar-item-admin',
  templateUrl: './agregar-item-admin.component.html',
  styleUrls: ['./agregar-item-admin.component.css']
})
export class AgregarItemAdminComponent implements OnInit{
  ngOnInit(): void {
    this.limpiar();
  }

  constructor(private andService:AndService){}


  nuevoForm = new FormGroup({
    itemCode: new FormControl('',Validators.required),
    ncmCode:new FormControl('',Validators.required),
    itemName : new FormControl('',Validators.required),
    itemType:new FormControl(''),
    taxVariable:new FormControl(true),
    taxType:new FormControl(true),
    vatLiable:new FormControl(true),
    cardCode:new FormControl(''),
    itmsGrpCod:new FormControl(''),
    sVolume:new FormControl(''),
    sWeight11:new FormControl(''),
    sWght1Unit:new FormControl(''),
    sWeight1:new FormControl(''),
    invntryUom:new FormControl(''),
    iWeight1:new FormControl(''),
    numInSale:new FormControl(''),
    planingSys:new FormControl(''),
    prcrmntMtd:new FormControl(''),
    codeBars:new FormControl(''),
    uClasifStore:new FormControl(''),
    uCode:new FormControl(''),
    salUnitMsr:new FormControl(''),
    salPackUn:new FormControl(''),
    buyUnitMsr:new FormControl(''),
    purPackMsr:new FormControl(''),
    salPackMsr:new FormControl(''),
    sww:new FormControl(''),
    cat_Linea:new FormControl(),
    cat_Mixto:new FormControl(),
    cat_Casa:new FormControl(),
    cat_ProductoN:new FormControl(true),
    cat_LAColors:new FormControl(),
    cat_RubyRose:new FormControl(),
    cat_CabelloApple:new FormControl(),
    cat_CosmeticoMega:new FormControl(),
    cat_IMNatural:new FormControl(),
    cat_Curtis:new FormControl(),
    cat_Moda:new FormControl(),
    cat_Temporada:new FormControl(),
    cat_AretesP:new FormControl(),
    cat_AnilloP:new FormControl(),
    cat_Collar:new FormControl(),
    cat_AccesoriosApple:new FormControl(),
    cat_PestanasApple:new FormControl(),
    cat_AplicadoresApple:new FormControl(),
    cat_DepiladoresApple:new FormControl(),
    cat_LapizAND:new FormControl(),
    cat_CosmeticosMega:new FormControl(),
    cat_DonasValerinas:new FormControl(),
    cat_BroPasCucas:new FormControl(),
    cat_PinzasDiademas:new FormControl(),
    cat_LigasColetero:new FormControl(),
    cat_Naturone:new FormControl(),
    cat_Prosa41: new FormControl(),
    cat_Postizas:new FormControl(),
    cat_Hogar:new FormControl(),
    cat_Cocina:new FormControl(),
    cat_Juguetes:new FormControl(),
    cat_Escritura:new FormControl(),
    cat_CortaPega:new FormControl(),
    cat_EmpaquesRegalo:new FormControl(),
    cat_Complementos:new FormControl(),
    cat_Ultramo:new FormControl(),
    cat_Remate:new FormControl(),
    cat_Importacion:new FormControl(),
    cat_TemSep:new FormControl(),
    cat_TemHallow:new FormControl(),
    cat_TemNavid:new FormControl(),
    cat_Fiesta:new FormControl(),
    cat_CajaCerrada:new FormControl(),
    cat_Nails:new FormControl(),
    cat_AccesoriosMegaline:new FormControl(),
    cat_AccesoriosAND:new FormControl(),
    cat_CabelloAND:new FormControl(),
    cat_CabelloMegaline:new FormControl(),
    cat_PestanaAND:new FormControl(),
    cat_DepiladoresAND:new FormControl(),
    cat_AplicadoresAND:new FormControl(),
    cat_HebleeCosmetics:new FormControl(),
    cat_Marcas:new FormControl(),
    cat_Rostro:new FormControl(),
    cat_Ojos:new FormControl(),
    cat_Labios:new FormControl(),
    cat_CuidadoPiel:new FormControl(),
    cat_AccesorioBelleza:new FormControl(),
    cat_Bissu:new FormControl(),
    cat_Maravilla:new FormControl(),
    cat_ByApple:new FormControl(),
    cat_Saniye:new FormControl(),
    cat_Pink21:new FormControl(),
    cat_AmorUS:new FormControl(),
    cat_DanzonCosmetics:new FormControl()
  });
  
  listaNCM: NCMCodeI[] = [

    new NCMCodeI("26126", "49101614", "Máscaras rituales o para teatro"),
    new NCMCodeI("24265", "43221703", "Antenas de televisión"),
    new NCMCodeI("24523", "43232503", "Correctores de ortografía"),
    new NCMCodeI("24899", "44121604", "Estampillas"),
    new NCMCodeI("24941", "44121716", "Resaltadores"),
    new NCMCodeI("25417", "46161602", "Salvavidas"),
    new NCMCodeI("25419", "46161604", "Chalecos o protectores salvavidas"),
    new NCMCodeI("25842", "47131600", "Escobas, traperos, cepillos y accesorios"),
    new NCMCodeI("24677", "44101809", "Calculadoras de escritorio"),
    new NCMCodeI("24905", "44121615", "Grapadoras"),
    new NCMCodeI("24947", "44121800", "Medios de corrección"),
    new NCMCodeI("25504", "46181504", "Guantes de protección"),
    new NCMCodeI("25548", "46181604", "Botas de seguridad"),
    new NCMCodeI("25587", "46182001", "Máscaras o accesorios"),
    new NCMCodeI("25840", "47131502", "Pañitos o toallas para limpiar"),
    new NCMCodeI("25883", "47131812", "Refrescador de aire"),
    new NCMCodeI("26122", "49101609", "Ornamentos o decoraciones"),
    new NCMCodeI("24631", "44101600", "Máquinas para procesamiento de papel y accesorios"),
    new NCMCodeI("24675", "44101807", "Calculadoras de bolsillo"),
    new NCMCodeI("24707", "44102305", "Tensionadores o selladoras para zunchado"),
    new NCMCodeI("24874", "44111912", "Borradores para tableros blancos"),
    new NCMCodeI("24908", "44121619", "Tajalápices manuales"),
    new NCMCodeI("24915", "44121801", "Removedor de adhesivo"),
    new NCMCodeI("24948", "44121626", "Película o cinta de corrección"),
    new NCMCodeI("25451", "46171515", "Cadenas de llaves o estuches de llaves"),
    new NCMCodeI("25845", "47131603", "Esponjas"),
    new NCMCodeI("25968", "48101600", "Equipos para preparado de alimentos"),
    new NCMCodeI("26045", "48101919", "Vasos o tazas o tazones (mugs) o tapas de contenedores para servicio de comidas"),
    new NCMCodeI("22543", "42211808", "Cortaúñas o limas para los discapacitados físicamente"),
    new NCMCodeI("22752", "42241700", "Productos blandos ortopédicos para la extremidad inferior"),
    new NCMCodeI("23932", "43191600", "Partes o accesorios de dispositivos de comunicación personal"),
    new NCMCodeI("22762", "42241800", "Productos blando ortopédicos para el torso y extremidad superior"),
    new NCMCodeI("26113", "49101600", "Coleccionables"),
    new NCMCodeI("24413", "43223303", "Cable de conexión de comunicación de datos"),
    new NCMCodeI("24898", "44121600", "Suministros de escritorio"),
    new NCMCodeI("24907", "44121618", "Tijeras"),
    new NCMCodeI("26825", "50211502", "Cigarrillos o cigarros"),
    new NCMCodeI("23943", "43191611", "Protectores de líneas telefónicas"),
    new NCMCodeI("24710", "44102400", "Etiquetadoras"),
    new NCMCodeI("24887", "44121503", "Sobres"),
    new NCMCodeI("24995", "44122100", "Suministros de sujeción"),
    new NCMCodeI("25169", "45121504", "Cámaras digitales"),
    new NCMCodeI("25838", "47131500", "Trapos y paños de limpieza"),
    new NCMCodeI("26032", "48101906", "Canastas para servir para servicio de comidas"),
    new NCMCodeI("1", "01010101", "No existe en el catálogo"),
    new NCMCodeI("8298	", "12131707	", "Encendedores"),
    new NCMCodeI("24932", "	44121707", "	Lápices de colores"),
    new NCMCodeI("24998", "	44122104", "	Clips para papel"),
    new NCMCodeI("25543", "	46181552", "	Lámpara de cabeza para minería"),
    new NCMCodeI("50	1", "0111300", "Accesorios, equipo y tratamientos para los animales domésticos"),
    new NCMCodeI("26028", "	48101902", "	Cubertería para servicio de comidas"),
    new NCMCodeI("11220", "	24112602", "	Frascos"),
    new NCMCodeI("8647	", "12171703	", "Tintas"),
    new NCMCodeI("8974	", "14111537	", "Etiquetas de papel"),
    new NCMCodeI("24104", "	43202215", "	Cable de teclado o mouse"),
    new NCMCodeI("24882", "	44112006", "	Diarios o repuestos"),
    new NCMCodeI("24890", "	44121506", "	Sobres estándar"),
    new NCMCodeI("11147", "	24111503", "	Bolsas plásticas"),
    new NCMCodeI("11239", "	24121503", "	Cajas para empacar"),
    new NCMCodeI("11246", "	24121511", "	Cartón de empacar"),
    new NCMCodeI("8982	", "14111601	", "Papel o bolsas o cajas de regalo"),
    new NCMCodeI("12370", "	26111702", "	Pilas alcalinas"),
    new NCMCodeI("13205", "	27112831", "	Accesorios y suministros de llave"),
    new NCMCodeI("24633", "	44101602", "	Máquinas perforadoras o para unir papel"),
    new NCMCodeI("24824", "	44111521", "	Sujetadores de copias"),
    new NCMCodeI("24956", "	44121900", "	Repuestos de tinta y minas de lápices"),
    new NCMCodeI("25001", "	44122107", "	Grapas"),
    new NCMCodeI("25851", "	47131611", "	Recogedor de basura"),
    new NCMCodeI("25878", "	47131807", "	Blanqueadores"),
    new NCMCodeI("26026", "	48101900", "	Tazas para servicio de mesa"),
    new NCMCodeI("8954	", "14111514	", "Blocs o cuadernos de papel"),
    new NCMCodeI("11623", "	25171502", "	limpiaparabrisas para automóviles"),
    new NCMCodeI("12474", "	26121600", "	Cables eléctricos y accesorios"),
    new NCMCodeI("24812", "	44111509", "	Sujetadores de esferos o lápices"),
    new NCMCodeI("24963", "	44122000", "	Carpetas de archivo, carpetas y separadores"),
    new NCMCodeI("25437", "	46171501", "	Candados"),
    new NCMCodeI("25506", "	46181506", "	Ponchos de protección"),
    new NCMCodeI("25580", "	46181811", "	Lentes protectores"),
    new NCMCodeI("51", "10111301", "Juguetes para mascotas"),
    new NCMCodeI("12714", "27111505", "Sets para manicure"),
    new NCMCodeI("23702", "42311511", "Vendajes de gasa"),
    new NCMCodeI("24889", "44121505", "Sobres especiales"),
    new NCMCodeI("26389", "49221510", "Gorras deportivas"),
    new NCMCodeI("52", "10111302", "Productos para el aseo y cuidado de mascotas"),
    new NCMCodeI("8611", "12171500", "Tintes"),
    new NCMCodeI("9003", "14111706", "Manteles de papel"),
    new NCMCodeI("12870", "27111811", "Regla doblable"),
    new NCMCodeI("47188", "56101545", "Espejos decorativos"),
    new NCMCodeI("47400", "56131701", "Barras para colgar artículos"),
    new NCMCodeI("48228", "60121200", "Pintura del aula y de bellas artes, medios, aplicadores y accesorios"),
    new NCMCodeI("312", "10191703", "Trampas para el control de insectos voladores"),
    new NCMCodeI("8651", "12181503", "Parafinas"),
    new NCMCodeI("11157", "24111514", "Bolsas con cremallera"),
    new NCMCodeI("11217", "24112505", "Formas de cartón corrugado"),
    new NCMCodeI("11260", "24122002", "Botellas de plástico"),
    new NCMCodeI("11318", "24141605", "Materiales de empaque rellenos de aire"),
    new NCMCodeI("17584", "39101600", "Lámparas y bombillas"),
    new NCMCodeI("24926", "44121701", "Bolígrafos"),
    new NCMCodeI("24966", "44122003", "Carpetas"),
    new NCMCodeI("24976", "44122016", "Sujetador de documentos"),
    new NCMCodeI("25210", "45121624", "Reflector de luz para fotografía"),
    new NCMCodeI("25818", "47121800", "Equipo de limpieza"),
    new NCMCodeI("25978", "48101610", "Peladores para uso comercial"),
    new NCMCodeI("314", "10191705", "Lazos"),
    new NCMCodeI("8940", "14111500", "Papel de imprenta y papel de escribir"),
    new NCMCodeI("47167", "56101523", "Paragüeros o soportes para paraguas"),
    new NCMCodeI("12994", "27112100", "Herramientas de sujeción y fijación"),
    new NCMCodeI("48168", "60121009", "Vasija decorativa"),
    new NCMCodeI("48335", "60121535", "Borradores de goma"),
    new NCMCodeI("48736", "60141000", "Juguetes"),
    new NCMCodeI("8981", "14111600", "Papel fantasía"),
    new NCMCodeI("12773", "27111602", "Martillos"),
    new NCMCodeI("47379", "56121902", "Stands exhibidores"),
    new NCMCodeI("48289", "60121401", "Marcos de madera preensamblados"),
    new NCMCodeI("48141", "60111300", "Letras y números decorativos"),
    new NCMCodeI("48167", "60121008", "Afiches"),
    new NCMCodeI("23933", "43191601", "Placas frontales de teléfonos móviles"),
    new NCMCodeI("24033", "43201800", "Dispositivos de almacenamiento"),
    new NCMCodeI("24971", "44122011", "Folders"),
    new NCMCodeI("25872", "47131801", "Limpiadores de pisos"),
    new NCMCodeI("25874", "47131803", "Desinfectantes para uso doméstico"),
    new NCMCodeI("101", "10131604", "Correas para perros"),
    new NCMCodeI("8951 ", "14111511	", "Papel de escritura"),
    new NCMCodeI("12794", "27111700", "	Llaves inglesas y guías"),
    new NCMCodeI("13900", "30181600", "	Instalaciones residenciales no sanitarias"),
    new NCMCodeI("17726", "39112011", "	Árbol o hilo de luz"),
    new NCMCodeI("50624", "78102200", "	Servicios postales de paqueteo y courrier"),
    new NCMCodeI("48741", "60141005", "	Casas de juego"),
    new NCMCodeI("18305", "40141600", "	Válvulas"),
    new NCMCodeI("19859", "41111500", "	Instrumentos de medición del peso"),
    new NCMCodeI("15665", "31181800", "	Cubiertas automotrices"),
    new NCMCodeI("46476", "52151611", "	Pinzas de cocina para uso doméstico"),
    new NCMCodeI("46567", "52152004", "	Platos para uso doméstico"),
    new NCMCodeI("23075", "42281600", "	Soluciones de desinfectantes y esterilización en frío"),
    new NCMCodeI("24786", "44103124", "	Cinta térmica"),
    new NCMCodeI("24936", "44121711", "	Rotuladores"),
    new NCMCodeI("24996", "44122101", "	Cauchos"),
    new NCMCodeI("8967", "14111530", "	Papel de notas autoadhesivas"),
    new NCMCodeI("12368", "26111700", "	Baterías, pilas y accesorios"),
    new NCMCodeI("12711", "27111502", "	Navajas de afeitar"),
    new NCMCodeI("12713", "27111504", "	Navajas de bolsillo"),
    new NCMCodeI("13145", "27112719", "	Pistolas para engomar"),
    new NCMCodeI("17928", "39121522", "	Contactos eléctricos"),
    new NCMCodeI("18259", "40101825", "	Calentadores de agua para uso doméstico"),
    new NCMCodeI("48175", "60121100", "	Lienzos, películas, tableros y papeles de artista"),
    new NCMCodeI("21161", "42141500", "	Bolas de algodón y copitos aplicadores"),
    new NCMCodeI("51944", "90101600", "	Servicios de banquetes y catering"),
    new NCMCodeI("10518", "23181600", "	Maquinaria para corte de alimentos"),
    new NCMCodeI("8990", "14111611", "	Tarjetas de invitación o de anuncio"),
    new NCMCodeI("12709", "27111500", "Herramientas de corte y engarzado y punzones"),
    new NCMCodeI("13126", "27112700", "Herramientas mecánicas"),
    new NCMCodeI("48148", "60111400", "Decoraciones especiales para el aula y accesorios decorativos"),
    new NCMCodeI("48514", "60124317", "Masa para modelado"),
    new NCMCodeI("50921", "80151500", "Facilitación del comercio"),
    new NCMCodeI("21130", "42131606", "Máscaras quirúrgicas o de aislamiento para personal médico"),
    new NCMCodeI("21332", "42142902", "Lentes para anteojos"),
    new NCMCodeI("15823", "31211910", "Guantes para pintar"),
    new NCMCodeI("46469", "52151604", "Coladores o coladeras para uso doméstico"),
    new NCMCodeI("46474", "52151609", "Peladora de vegetales"),
    new NCMCodeI("46532", "52151703", "Tenedores para uso doméstico"),
    new NCMCodeI("46356", "52121703", "Paños para lavar"),
    new NCMCodeI("46570", "52152007", "Tazones para servir para uso doméstico"),
    new NCMCodeI("46581", "52152018", "Loncheras"),
    new NCMCodeI("47409", "56141601", "Tazones de vidrio"),
    new NCMCodeI("48461", "60123204", "Cintas decorativas"),
    new NCMCodeI("48778", "60141115", "Kits de juegos"),
    new NCMCodeI("20407", "41113686", "Medidor de pulso"),
    new NCMCodeI("51542", "84111506", "Servicios de facturación"),
    new NCMCodeI("15401", "31162405", "Tensores"),
    new NCMCodeI("15695", "31201502", "Cinta aislante eléctrica"),
    new NCMCodeI("46528", "52151663", "Mortero para moler alimentos"),
    new NCMCodeI("46855", "53131503", "Cepillos de dientes"),
    new NCMCodeI("17185", "31401502", "Empaque moldeado de plástico"),
    new NCMCodeI("47187", "56101544", "Espejos"),
    new NCMCodeI("47294", "56112104", "Sillas para ejecutivos"),
    new NCMCodeI("48738", "60141002", "Muñecas"),
    new NCMCodeI("19946", "41111714", "Lupas"),
    new NCMCodeI("50662", "78121603", "Tarifa de los fletes"),
    new NCMCodeI("51215", "82101500", "Publicidad impresa"),
    new NCMCodeI("15883", "31241501", "Lentes"),
    new NCMCodeI("8829	", "13111008	", "esina acetato vinilo etileno"),
    new NCMCodeI("12716", "27111507", "Cortadores de metal"),
    new NCMCodeI("13251", "27113200", "Juegos de herramientas"),
    new NCMCodeI("13901", "30181601", "Jabonera"),
    new NCMCodeI("18206", "40101604", "Ventiladores"),
    new NCMCodeI("47168", "56101524", "Mesas de plancha"),
    new NCMCodeI("47655", "60102910", "Alcancía de monedas"),
    new NCMCodeI("48165", "60121006", "Cuadros"),
    new NCMCodeI("48324", "60121520", "Carboncillos"),
    new NCMCodeI("48349", "60121701", "Sellos de estampación de caucho"),
    new NCMCodeI("48579", "60131203", "Flautas musicales"),
    new NCMCodeI("48581", "60131205", "Cornetas musicales"),
    new NCMCodeI("48740", "60141004", "Animales o títeres de peluche"),
    new NCMCodeI("46323", "52101511", "Tapetes de caucho o vinilo"),
    new NCMCodeI("46400", "52141527", "Cuchillos eléctricos para uso doméstico"),
    new NCMCodeI("46728", "53102503", "Sombreros"),
    new NCMCodeI("46875", "53131612", "Geles de baño"),
    new NCMCodeI("46893", "53131630", "Bálsamo labial"),
    new NCMCodeI("46901", "53131638", "Esmalte para uñas"),
    new NCMCodeI("15710", "31201517", "Cinta para empaquetar"),
    new NCMCodeI("15896", "31241700", "Espejos"),
    new NCMCodeI("46320", "52101508", "Tapetes de entrada"),
    new NCMCodeI("46453", "52141804", "Ventiladores eléctricos para uso doméstico"),
    new NCMCodeI("46456", "52141807", "Abanicos de mano"),
    new NCMCodeI("46531", "52151702", "Cuchillos para uso doméstico"),
    new NCMCodeI("24979", "44122019", "Bolsillos para archivos o accesorios"),
    new NCMCodeI("25604", "46182201", "Cinturones de soporte de la espalda"),
    new NCMCodeI("26005", "48101800", "Menaje y utensilios de cocina"),
    new NCMCodeI("313	", "10191704", "Matamoscas"),
    new NCMCodeI("8650	", "12181502", "Ceras naturales"),
    new NCMCodeI("8909	", "13111201", "Películas de polietileno"),
    new NCMCodeI("11852", "	25174400", "Sistemas del interior de vehículos"),
    new NCMCodeI("12795", "	27111701", "Destornilladores"),
    new NCMCodeI("13907", "	30181607", "Cortina de baño o su ensamble"),
    new NCMCodeI("18379", "40141742", "Atomizadores"),
    new NCMCodeI("46348", "52121604", "Manteles"),
    new NCMCodeI("46541", "52151802", "Sartenes para uso doméstico"),
    new NCMCodeI("46583", "52152101", "Tazas de café o té para uso doméstico"),
    new NCMCodeI("46641", "52161554", "Audífono"),
    new NCMCodeI("12372", "26111704", "Cargadores de baterías"),
    new NCMCodeI("17721", "39112006", "Lámpara de mano portátil"),
    new NCMCodeI("17762", "39112604", "Velas de cera"),
    new NCMCodeI("48294", "60121406", "Marcos de plástico"),
    new NCMCodeI("18478", "40151501", "Bombas de aire"),
    new NCMCodeI("15409", "31162414", "Abrazadera"),
    new NCMCodeI("15426", "31162600", "Ganchos"),
    new NCMCodeI("46406", "52141533", "Planchas eléctricas para uso doméstico"),
    new NCMCodeI("46854", "53131502", "Dentífrico"),
    new NCMCodeI("46881", "53131618", "Implementos para la pedicura"),
    new NCMCodeI("46913", "53131702", "Máquina masajeadora"),
    new NCMCodeI("46973", "54101602", "Collares"),
    new NCMCodeI("47402", "56131703", "Ganchos o cascadas exhibidoras"),
    new NCMCodeI("48254", "60121226", "Pinceles para acuarela"),
    new NCMCodeI("48397", "60122003", "Agujas para coser a mano"),
    new NCMCodeI("52602", "95101600", "Lotes comerciales"),
    new NCMCodeI("15818", "31211904", "Brochas"),
    new NCMCodeI("46602", "52161512", "Altoparlantes"),
    new NCMCodeI("46859", "53131507", "Palillos de dientes (mondadientes)"),
    new NCMCodeI("46868", "53131605", "Kits de tocador"),
    new NCMCodeI("46869", "53131606", "Desodorantes"),
    new NCMCodeI("46919", "53141502", "Imperdibles"),
    new NCMCodeI("47078", "55121600", "Etiquetas"),
    new NCMCodeI("48216", "60121142", "Cartón duro o cartón de colores de dos caras"),
    new NCMCodeI("18287", "40101902", "Deshumidificadores"),
    new NCMCodeI("50917", "80141900", "Exhibiciones y ferias comerciales"),
    new NCMCodeI("15747", "31201616", "Adhesivos líquidos"),
    new NCMCodeI("46461", "52151504", "Tazas o vasos o tapas desechables para uso doméstico"),
    new NCMCodeI("46563", "52152000", "Platos, utensilios para servir y recipientes para almacenar"),
    new NCMCodeI("46730", "53102505", "Sombrillas"),
    new NCMCodeI("46871", "53131608", "Jabones                               "),
    new NCMCodeI("46929", "53141603", "Dedales"),
    new NCMCodeI("47022", "55101500", "Publicaciones impresas"),
    new NCMCodeI("47083", "55121606", "Etiquetas auto adhesivas"),
    new NCMCodeI("47147", "56101500", "Muebles"),
    new NCMCodeI("46471", "52151606", "Tablas para cortar para uso doméstico"),
    new NCMCodeI("46481", "52151616", "Espátulas de cocina para uso doméstico"),
    new NCMCodeI("46805", "53111800", "Sandalias"),
    new NCMCodeI("46837", "53121605", "Monederos"),
    new NCMCodeI("46840", "53121608", "Bolsas para compras"),
    new NCMCodeI("46888", "53131625", "Redecillas para el cabello o la barba"),
    new NCMCodeI("46891", "53131628", "Champús"),
    new NCMCodeI("46753", "53102700", "Uniformes"),
    new NCMCodeI("46835", "53121602", "Tulas"),
    new NCMCodeI("46866", "53131603", "Afeitadoras"),
    new NCMCodeI("46884", "53131621", "Corta uñas"),
    new NCMCodeI("46894", "53131631", "Tatuajes"),
    new NCMCodeI("46984", "54111500", "Relojes de pulsera o bolsillo"),
    new NCMCodeI("46569", "52152006", "Bandejas o fuentes para uso doméstico"),
    new NCMCodeI("46851", "53121804", "Estuches de maquillaje o manicure"),
    new NCMCodeI("46867", "53131604", "Cepillos o peinillas para el cabello"),
    new NCMCodeI("46533", "52151704", "Cucharas para uso doméstico"),
    new NCMCodeI("46535", "52151706", "Palillos"),
    new NCMCodeI("46576", "52152013", "Saleros, pimenteros o especieros"),
    new NCMCodeI("46818", "53112001", "Calzadores"),
    new NCMCodeI("46895", "53131632", "Marrones calientes"),
    new NCMCodeI("46928", "53141602", "Kits de costura"),
    new NCMCodeI("46912", "53131701", "Unidad masajeadora manual"),
    new NCMCodeI("46931", "53141605", "Agujas de costura"),
    new NCMCodeI("47036", "55101517", "Dibujos dimensionales o de tolerancia"),
    new NCMCodeI("47377", "56121900", "Mobiliario de demostración"),
    new NCMCodeI("47393", "56131602", "Postes de exhibición individuales"),
    new NCMCodeI("50881", "80141605", "Mercancía promocional"),
    new NCMCodeI("21155", "42132200", "Guantes y accesorios médicos"),
    new NCMCodeI("15693", "31201500", "Cinta adhesiva"),
    new NCMCodeI("46433", "52141605", "Canastas de ropa"),
    new NCMCodeI("46465", "52151600", "Utensilios de cocina domésticos"),
    new NCMCodeI("52484", "94101609", "Asociaciones científicas"),
    new NCMCodeI("46722", "53102402", "Calcetines"),
    new NCMCodeI("46864", "53131601", "Gorros de baño"),
    new NCMCodeI("46865", "53131602", "Artículos para el cuidado del cabello"),
    new NCMCodeI("18437", "40142008", "Mangueras de agua"),
    new NCMCodeI("46470", "52151605", "Destapadores o abrelatas para uso doméstico"),
    new NCMCodeI("46565", "52152002", "Contenedores para almacenar alimentos para uso doméstico"),
    new NCMCodeI("46863", "53131600", "Baño y cuerpo"),
    new NCMCodeI("46466", "52151601", "Rodillos para uso doméstico"),
    new NCMCodeI("46501", "52151636", "Palas o cucharas para alimentos para uso doméstico"),
    new NCMCodeI("46725", "53102500", "Accesorios de vestir"),
    new NCMCodeI("21163", "42141502", "Palitos (copitos) con punta de fibra"),
    new NCMCodeI("46889", "53131626", "Desinfectante de manos"),
    new NCMCodeI("46907", "53131644", "Aceites esenciales de aromaterapia"),
    new NCMCodeI("47029", "55101507", "Libros para pintar o colorear o ilustrar para niños"),
    new NCMCodeI("46727", "53102502", "Corbatas o pañoletas o bufandas"),
    new NCMCodeI("46741", "53102516", "Gorras"),
    new NCMCodeI("46834", "53121601", "Bolsos o carteras"),
    new NCMCodeI("46870", "53131607", "Lociones o aceites para manos o cuerpo"),
    new NCMCodeI("46876", "53131613", "Productos para el cuidado de la piel"),
    new NCMCodeI("46883", "53131620", "Perfumes o colonias o fragancias"),
    new NCMCodeI("26622", "50161815", "Goma de mascar"),
    new NCMCodeI("24756", "44102912", "Soluciones limpiadoras para equipos de oficina"),
    new NCMCodeI("24925", "44121700", "Instrumentos de escritura"),
    new NCMCodeI("48737", "60141001", "Globos o pelotas de juguete"),
    new NCMCodeI("48784", "60141202", "Piscinas de pelotas y accesorios"),
    new NCMCodeI("17867", "39121402", "Enchufes eléctricos"),
    new NCMCodeI("52037", "91101600", "Cuidado facial y corporal"),
    new NCMCodeI("15705", "31201512", "Cinta transparente"),
    new NCMCodeI("46344", "52121600", "Mantelerías de cocina y mesa y accesorios"),
    new NCMCodeI("46564", "52152001", "Jarras para uso doméstico"),
    new NCMCodeI("46604", "52161514", "Audífonos"),
    new NCMCodeI("46732", "53102507", "Ganchos para colgar la ropa"),
    new NCMCodeI("46857", "	53131505", "	Chupos o chupetes para bebé"),
    new NCMCodeI("46880", "	53131617", "	Implementos para la manicure"),
    new NCMCodeI("46882", "	53131619", "	Cosméticos"),
    new NCMCodeI("46887", "	53131624", "	Paños limpiadores desechables"),
    new NCMCodeI("46971", "	54101600", "	Bisutería"),
    new NCMCodeI("46896", "	53131633", "	Hebillas para el pelo"),
    new NCMCodeI("46906", "	53131643", "	Cortador de pelo eléctrico"),
    new NCMCodeI("24933", "	44121708", "	Marcadores"),
    new NCMCodeI("24949", "	44121802", "	Fluido de corrección"),
    new NCMCodeI("24999", "	44122105", "	Clips para carpetas o bulldog"),
    new NCMCodeI("25165", "	45121500", "	Cámaras"),
    new NCMCodeI("25544", "	46181600", "	Calzado de protección"),
    new NCMCodeI("25819", "	47121801", "	Plumeros para limpiar el polvo"),
    new NCMCodeI("8120", "11151700	", "Hilos"),
    new NCMCodeI("8787", "13101900	", "Plásticos termoformados"),
    new NCMCodeI("8947", "14111507	", "Papel para impresora o fotocopiadora"),
    new NCMCodeI("11237", "24121500", "Cajas, bolsas y sacos para empaquetado"),
    new NCMCodeI("11296", "24141501", "Película elástica para envoltura"),
    new NCMCodeI("17898", "39121440", "Cable de extensión eléctrica"),
    new NCMCodeI("50085", "73101505", "Servicios de fabricación de plásticos, resinas o fibras"),
    new NCMCodeI("50603", "78101800", "Transporte de carga por carretera"),
    new NCMCodeI("20506", "41114201", "	Cintas medidoras"),
    new NCMCodeI("15708", "31201515", "	Cintas de papel"),
    new NCMCodeI("15731", "31201600", "	Otros adhesivos y selladores"),
    new NCMCodeI("15741", "31201610", "Pegamentos"),
    new NCMCodeI("15882", "31241500", "Lentes y prismas"),
    new NCMCodeI("46442", "52141701", "Cepillos de dientes eléctricos para uso doméstico"),
    new NCMCodeI("46584", "52152102", "Vasos para beber para uso doméstico"),
    new NCMCodeI("46726", "53102501", "Cinturones o tirantes"),
    new NCMCodeI("46833", "53121600", "Monederos, bolsos de mano y bolsas"),
    new NCMCodeI("46886", "53131623", "Productos depilatorios o para remover vello"),
    new NCMCodeI("46903", "53131640", "Removedor de esmalte"),
    new NCMCodeI("46968", "54101511", "Prendedores de joyería fina"),
    new NCMCodeI("47134", "55121804", "Gafetes o porta gafetes"),



  ];
  listaCodigoStore: CodigoSI[] = [
    new CodigoSI("A", "ALTO"),
    new CodigoSI("B", "MEDIO"),
    new CodigoSI("C", "BAJO"),
    new CodigoSI("N", "NUEVO"),
    new CodigoSI("O", "OBSOLETO"),
  ];
  listaClasif: ClasificacionI[] = [
    new ClasificacionI("ABANICO MADERA"),
    new ClasificacionI("ABANICO TEXTIL"),
    new ClasificacionI("ACETONA"),
    new ClasificacionI("ACUARELA"),
    new ClasificacionI("ALCANCIA"),
    new ClasificacionI("ALICATA ECONOMICA"),
    new ClasificacionI("ALICATA PREMIUM"),
    new ClasificacionI("ANILLO CABALLERO"),
    new ClasificacionI("ANILLO DAMA"),
    new ClasificacionI("ANILLO INFANTIL"),
    new ClasificacionI("ANILLO PARA CELULAR"),
    new ClasificacionI("APLICADOR DUO PARA SOMBRAS"),
    new ClasificacionI("ARETE BROQUEL"),
    new ClasificacionI("ARETE LARGO"),
    new ClasificacionI("ARETE MULTIPAR"),
    new ClasificacionI("ARRACADA INDIVIDUAL ECONOMICA"),
    new ClasificacionI("ARRACADA INDIVIDUAL PREMIUM"),
    new ClasificacionI("ARRACADA MULTIPAR"),
    new ClasificacionI("ATOMIZADOR DE PISTOLA"),
    new ClasificacionI("ATOMIZADOR DE VALVULA"),
    new ClasificacionI("ATOMIZADOR DESPACHADOR/CREMA SHAMPOO"),
    new ClasificacionI("ATOMIZADOR PERFUMERO"),
    new ClasificacionI("AUDIFONO ECONOMICO"),
    new ClasificacionI("AUDIFONO PREMIUM"),
    new ClasificacionI("BALON DEPORTIVO"),
    new ClasificacionI("BANANA ECONOMICA"),
    new ClasificacionI("BANANA PREMIUM"),
    new ClasificacionI("BARAJA ESPAÑOLA"),
    new ClasificacionI("BARAJA POKER"),
    new ClasificacionI("BATE"),
    new ClasificacionI("BILLETE DE JUGUETE"),
    new ClasificacionI("BLOQUEADOR SOLAR"),
    new ClasificacionI("BOLSA DE REGALO CABALLERO"),
    new ClasificacionI("BOLSA DE REGALO DAMA"),
    new ClasificacionI("BOLSA DE REGALO FELIZ CUMPLEAÑOS"),
    new ClasificacionI("BOLSA DE REGALO GENERICA"),
    new ClasificacionI("BOLSA DE REGALO HOLOGRAMA"),
    new ClasificacionI("BOLSA DE REGALO INFANTIL"),
    new ClasificacionI("BOLSA DE REGALO NACIONAL CH"),
    new ClasificacionI("BOLSA DE REGALO NACIONAL G"),
    new ClasificacionI("BOLSA DE REGALO NACIONAL J "),
    new ClasificacionI("BOLSA DE REGALO NACIONAL M"),
    new ClasificacionI("BOLSA DE REGALO NIÑA"),
    new ClasificacionI("BOLSA DE REGALO NIÑO"),
    new ClasificacionI("BOLSA DE REGALO TEMPORADA /14 FEB NAVIDAD"),
    new ClasificacionI("BOLSA ECOLOGICA CAMISETA-OREJAS"),
    new ClasificacionI("BOLSA PLASTIFICADA"),
    new ClasificacionI("BOLSA POLIPAPEL"),
    new ClasificacionI("BOLSAS DE CELOFAN"),
    new ClasificacionI("BOMBA PARA GLOBOS"),
    new ClasificacionI("BORLA PARA BAÑO"),
    new ClasificacionI("BROCHA DUO CON CEPILLO"),
    new ClasificacionI("BROCHA ECONOMICA EN SET"),
    new ClasificacionI("BROCHA INDIVIDUAL DELGADA"),
    new ClasificacionI("BROCHA PARA POLVO GRUESA"),
    new ClasificacionI("BROCHA PARA TINTE CON PEINE"),
    new ClasificacionI("BROCHA PREMIUM EN SET"),
    new ClasificacionI("BROCHA TIPO CUCHARA"),
    new ClasificacionI("BROCHE FRANCES"),
    new ClasificacionI("BROCHE PARA CABELLO"),
    new ClasificacionI("BURBUJA DE JUGUETE"),
    new ClasificacionI("CABLE PARA CELULAR"),
    new ClasificacionI("CAJA DE REGALO ANILLO"),
    new ClasificacionI("CAJA DE REGALO CARTON MEDIANA"),
    new ClasificacionI("CAJA DE REGALO COLLAR"),
    new ClasificacionI("CAJA DE REGALO PULSERA"),
    new ClasificacionI("CALCETIN/PROTECTOR"),
    new ClasificacionI("CALCULADORA"),
    new ClasificacionI("CANICA BLANCA VERDE"),
    new ClasificacionI("CARGADORES PARA CELULAR CUBO & COCHE"),
    new ClasificacionI("CARRO DE JUGUETE"),
    new ClasificacionI("CARTERA CABALLERO"),
    new ClasificacionI("CARTERA DAMA"),
    new ClasificacionI("CARTERA DE MAQUILLAJE"),
    new ClasificacionI("CARTERA INFANTIL NIÑO- NIÑA"),
    new ClasificacionI("CASA"),
    new ClasificacionI("CASCADA PARA CABELLO ECONOMICA"),
    new ClasificacionI("CASCADA PARA CABELLO PREMIUM"),
    new ClasificacionI("CEPILLO ABANICO COLORES Y NEGRO"),
    new ClasificacionI("CEPILLO CON ESPEJO"),
    new ClasificacionI("CEPILLO DE MADERA"),
    new ClasificacionI("CEPILLO DENTAL ADULTO- NIÑO"),
    new ClasificacionI("CEPILLO EXFOLIANTE"),
    new ClasificacionI("CEPILLO MANICURE"),
    new ClasificacionI("CEPILLO PARA CABELLO ECONOMICO"),
    new ClasificacionI("CEPILLO PARA CABELLO PREMIUM"),
    new ClasificacionI("CEPILLO PARA ROPA"),
    new ClasificacionI("CEPILLO REDONDO"),
    new ClasificacionI("CETRO INFANTIL"),
    new ClasificacionI("CINTA DE AISLAR"),
    new ClasificacionI("CINTA DIUREX"),
    new ClasificacionI("CINTA PARA EMPACAR"),
    new ClasificacionI("COFIA CH G"),
    new ClasificacionI("COLADOR DE COCINA"),
    new ClasificacionI("COLAGENO MASCARILLA"),
    new ClasificacionI("COLAGENO POMULOS"),
    new ClasificacionI("COLETERO"),
    new ClasificacionI("COLLAR ECONOMICO"),
    new ClasificacionI("COLLAR PREMIUM"),
    new ClasificacionI("CONTORNEADOR"),
    new ClasificacionI("CORONA INFANTIL"),
    new ClasificacionI("CORRECTOR EN BARRA"),
    new ClasificacionI("CORRECTOR LIQUIDO"),
    new ClasificacionI("CORTA UÑAS  M 7CM"),
    new ClasificacionI("CORTA UÑAS ALICATA"),
    new ClasificacionI("CORTA UÑAS CH 5CM"),
    new ClasificacionI("CORTA UÑAS CON DESTAPADOR"),
    new ClasificacionI("CORTA UÑAS G 9CM"),
    new ClasificacionI("COSMETIQUERA"),
    new ClasificacionI("COTONETE"),
    new ClasificacionI("CRAYOLA"),
    new ClasificacionI("CRECENCIO JUGUETE"),
    new ClasificacionI("CREMA HUMECTANTE"),
    new ClasificacionI("CREMAS OTRAS"),
    new ClasificacionI("CUADRITELA"),
    new ClasificacionI("CUBO RUBIK MEDIANO"),
    new ClasificacionI("CUCA DECORADA"),
    new ClasificacionI("CUCA EN TIRA"),
    new ClasificacionI("CUCHARA CAFETERA"),
    new ClasificacionI("CUCHARA PARA SERVIR"),
    new ClasificacionI("CUCHARA SOPERA"),
    new ClasificacionI("CUCHILLO"),
    new ClasificacionI("CUCHILLO DE SIERRA"),
    new ClasificacionI("CUERDA JUGUETE"),
    new ClasificacionI("CUTTER"),
    new ClasificacionI("DELINEADOR DE CEJA EN TARRO"),
    new ClasificacionI("DELINEADOR LIQUIDO"),
    new ClasificacionI("DELINEADOR LIQUIDO CON GLITTER"),
    new ClasificacionI("DELINEADOR PLUMIN"),
    new ClasificacionI("DEPILADOR CAIMAN"),
    new ClasificacionI("DEPILADOR DE PINZA"),
    new ClasificacionI("DESMAQUILLANTE LIQUIDO"),
    new ClasificacionI("DIADEMA DE PLASTICO LISA CH M G, COLORES"),
    new ClasificacionI("DIADEMA MODA"),
    new ClasificacionI("DIBUJO PARA COLOREAR"),
    new ClasificacionI("DOMINO"),
    new ClasificacionI("DONA CHONGUERA"),
    new ClasificacionI("DONA CHONGUERA CH M G"),
    new ClasificacionI("DONA DE COCO"),
    new ClasificacionI("DONA MODA"),
    new ClasificacionI("DONA TOALLA GRANDE"),
    new ClasificacionI("DONA TOALLA MEDIANA"),
    new ClasificacionI("ENCENDEDOR"),
    new ClasificacionI("ENCHINADOR AULADO"),
    new ClasificacionI("ENCHINADOR GALENCO"),
    new ClasificacionI("ENCHINADOR MANGO PLASTICO GRUESO"),
    new ClasificacionI("ENCHINADOR METALICO NEGRO"),
    new ClasificacionI("ENCHINADOR METALICO NEGRO MANGO DE COLOR"),
    new ClasificacionI("ENCHINADOR METALICO PLATA"),
    new ClasificacionI("ENCHINADOR METALICO PLATA MANGO DE COLOR"),
    new ClasificacionI("ENCHINADOR PREMIUM"),
    new ClasificacionI("ERIZO CON LUZ"),
    new ClasificacionI("ESMALTE 15ML COLORES BASICOS"),
    new ClasificacionI("ESMALTE 15ML ESPEJO"),
    new ClasificacionI("ESMALTE 15ML GLITTER"),
    new ClasificacionI("ESMALTE 15ML MATE"),
    new ClasificacionI("ESMALTE MINI"),
    new ClasificacionI("ESPEJO DOBLE ECONOMICO"),
    new ClasificacionI("ESPEJO DOBLE PREMIUM"),
    new ClasificacionI("ESPEJO DUO ALMEJA"),
    new ClasificacionI("ESPEJO ECONOMICO"),
    new ClasificacionI("ESPEJO PREMIUM"),
    new ClasificacionI("ESPONJA APLICADORA ECONOMICA"),
    new ClasificacionI("ESPONJA APLICADORA PREMIUM"),
    new ClasificacionI("ESPONJA BLENDER BOLSA O CAJA"),
    new ClasificacionI("ETIQUETA EN ROLLO"),
    new ClasificacionI("ETIQUETADORA"),
    new ClasificacionI("EXFOLIANTE CORPORAL"),
    new ClasificacionI("EXTENSION DE CABELLO"),
    new ClasificacionI("EXTENSION ELECTRICA"),
    new ClasificacionI("FIBRA METALICA"),
    new ClasificacionI("FIBRA PLASTICA"),
    new ClasificacionI("FIBRA VERDE"),
    new ClasificacionI("FIJADOR DE MAQUILLAJE"),
    new ClasificacionI("FINANZAS"),
    new ClasificacionI("FLECHA CON LUZ"),
    new ClasificacionI("FOLDER"),
    new ClasificacionI("GANCHO METALICO DE EXHIBICIÓN"),
    new ClasificacionI("GEL ANTIBACTERIAL"),
    new ClasificacionI("GEL PARA CABELLO"),
    new ClasificacionI("GLOBO ANIMALES"),
    new ClasificacionI("GLOBO CORAZON"),
    new ClasificacionI("GLOBO ESTRELLA"),
    new ClasificacionI("GLOBO FELIZ CUMPLEAÑOS"),
    new ClasificacionI("GLOBO GUITARRA"),
    new ClasificacionI("GLOBO LETRA"),
    new ClasificacionI("GLOBO NUMERO"),
    new ClasificacionI("GLOSS PARA LABIOS"),
    new ClasificacionI("GOMA MIGAJON"),
    new ClasificacionI("GOMA TUBO"),
    new ClasificacionI("GUANTE DE USO RUDO"),
    new ClasificacionI("GUSANO JUGUETE CH G"),
    new ClasificacionI("HILO Y AGUJAS"),
    new ClasificacionI("ILUMINADOR"),
    new ClasificacionI("IMPERMEABLE"),
    new ClasificacionI("INCIENSO"),
    new ClasificacionI("JABON CORPORAL"),
    new ClasificacionI("JUEGOS DE MESA Y DESTREZA"),
    new ClasificacionI("JUGUETE CHILLON"),
    new ClasificacionI("JUGUETE DE AGUA TETRIS"),
    new ClasificacionI("JUGUETE DE ARENA"),
    new ClasificacionI("JUGUETE GRANDE"),
    new ClasificacionI("JUGUETE PEGAJOSO"),
    new ClasificacionI("JUGUETES OTROS"),
    new ClasificacionI("LABIAL DE BARRA ECONOMICO"),
    new ClasificacionI("LABIAL DE BARRA PREMIUM"),
    new ClasificacionI("LABIAL LIQUIDO"),
    new ClasificacionI("LABIAL PROTECTOR"),
    new ClasificacionI("LAMPARA"),
    new ClasificacionI("LAPICERA NIÑA NIÑO"),
    new ClasificacionI("LAPIZ COLORES DE MADERA CH G"),
    new ClasificacionI("LAPIZ DE CERA JUMBO"),
    new ClasificacionI("LAPIZ DE CERA JUNIOR"),
    new ClasificacionI("LAPIZ DELINEADOR CON GLITTER"),
    new ClasificacionI("LAPIZ DELINEADOR DE MADERA CAFÉ CLARO"),
    new ClasificacionI("LAPIZ DELINEADOR DE MADERA CAFÉ OSCURO"),
    new ClasificacionI("LAPIZ DELINEADOR DE MADERA SURTIDO"),
    new ClasificacionI("LAPIZ DELINEADOR MADERA NEGRO"),
    new ClasificacionI("LENTE AUMENTO"),
    new ClasificacionI("LENTE INFANTIL"),
    new ClasificacionI("LENTE SOLAR ADULTO"),
    new ClasificacionI("LIBRETA PASTA DURA"),
    new ClasificacionI("LIBRETA PASTA SUAVE"),
    new ClasificacionI("LIBRO PARA ILUMINAR"),
    new ClasificacionI("LIGA DE HULE"),
    new ClasificacionI("LIGA LATEX"),
    new ClasificacionI("LIGA LICRA"),
    new ClasificacionI("LIGA TEXTIL SWEET DOLL CORTA"),
    new ClasificacionI("LIGA TEXTIL SWEET DOLL LARGA"),
    new ClasificacionI("LIGA TPU"),
    new ClasificacionI("LIGA TUBO"),
    new ClasificacionI("LIMA 4 EN 1"),
    new ClasificacionI("LIMA CON PIEDRA Y CEPILLO"),
    new ClasificacionI("LIMA METALICA CON LIJA"),
    new ClasificacionI("LIMA NEGRA CH"),
    new ClasificacionI("LIMA NEGRA G"),
    new ClasificacionI("LIMA PARA PIES"),
    new ClasificacionI("LINEA"),
    new ClasificacionI("LLAVERO GENERAL"),
    new ClasificacionI("LLAVERO LASER"),
    new ClasificacionI("LUPA"),
    new ClasificacionI("MANGA PARA SOL"),
    new ClasificacionI("MANICURE SET"),
    new ClasificacionI("MANITA PEGAJOSA"),
    new ClasificacionI("MANITA RASCADORA"),
    new ClasificacionI("MAQUILLAJE EN POLVO (BANANA)"),
    new ClasificacionI("MAQUILLAJE FACIAL EN BARRA"),
    new ClasificacionI("MAQUILLAJE INFANTIL"),
    new ClasificacionI("MAQUILLAJE LIQUIDO ECONOMICO"),
    new ClasificacionI("MAQUILLAJE LIQUIDO PREMIUM"),
    new ClasificacionI("MARCA TEXTOS"),
    new ClasificacionI("MARCADOR PERMANENTE"),
    new ClasificacionI("MASCARA PARA PESTAÑAS"),
    new ClasificacionI("MASCARILLA COLAGENO"),
    new ClasificacionI("MASCARILLA LIQUIDA"),
    new ClasificacionI("MASCARILLA NEGRA CHICA"),
    new ClasificacionI("MASCARILLA TEXTIL"),
    new ClasificacionI("MATA MOSCAS"),
    new ClasificacionI("MOCO BARRIL"),
    new ClasificacionI("MONEDA DE JUGUETE"),
    new ClasificacionI("MONEDERO ECONOMICO"),
    new ClasificacionI("MONEDERO PREMIUM"),
    new ClasificacionI("MOÑO EN CARTERA"),
    new ClasificacionI("MOÑO PARA CABELLO"),
    new ClasificacionI("MOÑO PARA REGALO"),
    new ClasificacionI("MUÑECA MUÑECO DE JUGUETE"),
    new ClasificacionI("NAVAJA  MULTIUSOS"),
    new ClasificacionI("NAVAJA QUITA CAYOS"),
    new ClasificacionI("NUDO PARA CABELLO"),
    new ClasificacionI("OTROS ACCESORIOS DE CABELLO"),
    new ClasificacionI("OTROS BISUTERIA"),
    new ClasificacionI("OTROS COSMETICO Y BELLEZA"),
    new ClasificacionI("OTROS HOGAR Y COCINA"),
    new ClasificacionI("OTROS JUGUETES Y FIESTA"),
    new ClasificacionI("OTROS LINEAS"),
    new ClasificacionI("OTROS MODA Y TEMPORADA"),
    new ClasificacionI("OTROS PAPELERIA"),
    new ClasificacionI("PALA DE MADERA"),
    new ClasificacionI("PALETA DE MAQUILLAJE"),
    new ClasificacionI("PALILLO DE MADERA"),
    new ClasificacionI("PASADOR DECORADO"),
    new ClasificacionI("PASADOR EN CAJA"),
    new ClasificacionI("PASADOR EN TIRA"),
    new ClasificacionI("PASTILLERO PLASTICO"),
    new ClasificacionI("PEGAMENTO MULTIUSOS"),
    new ClasificacionI("PEGAMENTO PAPELERIA"),
    new ClasificacionI("PEGAMENTO PARA PESTAÑAS"),
    new ClasificacionI("PEGAMENTO PARA UÑAS"),
    new ClasificacionI("PEGAMENTO SUPER GLUE"),
    new ClasificacionI("PEINE CASPERO"),
    new ClasificacionI("PEINE PARA CABELLO"),
    new ClasificacionI("PEINETA MAGICA"),
    new ClasificacionI("PEINETA PARA CABELLO"),
    new ClasificacionI("PELADOR"),
    new ClasificacionI("PELOTA ANTI ESTRES"),
    new ClasificacionI("PELOTA CEREBRO"),
    new ClasificacionI("PELOTA DE AGUA CON LUZ"),
    new ClasificacionI("PELOTA DE PICOS CON LUZ"),
    new ClasificacionI("PELOTA PLASTICA ESTANDAR 20CM +"),
    new ClasificacionI("PELOTA SALTARINA"),
    new ClasificacionI("PERFILADOR  EN BLISTER"),
    new ClasificacionI("PERFILADOR EN BOLSA"),
    new ClasificacionI("PERFILADOR RETRACTIL"),
    new ClasificacionI("PERLA BRONCEADORAS"),
    new ClasificacionI("PESTAÑA ECONOMICA INDIVIDUAL"),
    new ClasificacionI("PESTAÑA ECONOMICA SET"),
    new ClasificacionI("PESTAÑA PREMIUM INDIVIDUAL"),
    new ClasificacionI("PESTAÑA PREMIUM SET"),
    new ClasificacionI("PICO DE GARZA"),
    new ClasificacionI("PILA"),
    new ClasificacionI("PINZA PARA ALIMENTOS"),
    new ClasificacionI("PINZA PARA APLICAR PESTAÑAS"),
    new ClasificacionI("PINZA PARA CABELLO ECONOMICA COLORES"),
    new ClasificacionI("PINZA PARA CABELLO ECONOMICA NEGRA"),
    new ClasificacionI("PINZA PARA CABELLO PREMIUM COLORES"),
    new ClasificacionI("PINZA PARA CABELLO PREMIUM NEGRA"),
    new ClasificacionI("PINZA PARA ROPA"),
    new ClasificacionI("PISTOLA DE AGUA"),
    new ClasificacionI("PISTOLA DE JUGUETE"),
    new ClasificacionI("PIZARRON DE JUGUETE"),
    new ClasificacionI("PLANTILLAS PARA CEJAS Y OJOS"),
    new ClasificacionI("PLASTILINA"),
    new ClasificacionI("PLATOS"),
    new ClasificacionI("PLUMA COLORES BASICOS"),
    new ClasificacionI("PLUMA DE MODA"),
    new ClasificacionI("PLUMA MAGICA"),
    new ClasificacionI("PLUMINES 6 12 Y 24"),
    new ClasificacionI("POCILLO"),
    new ClasificacionI("POLVO COMPACTO"),
    new ClasificacionI("POPOTE PARA GLOBO"),
    new ClasificacionI("POSTIT"),
    new ClasificacionI("PRIMER MAQUIJJALE"),
    new ClasificacionI("PROTECTOR PARA CELULAR"),
    new ClasificacionI("PULSERA CABALLERO"),
    new ClasificacionI("PULSERA DAMA"),
    new ClasificacionI("PULSERA NIÑA"),
    new ClasificacionI("QUITA CUTICULA"),
    new ClasificacionI("RASTRILLO"),
    new ClasificacionI("RAYADOR"),
    new ClasificacionI("REGLA"),
    new ClasificacionI("RELOJ"),
    new ClasificacionI("REPUESTO DE ENCHINADOR"),
    new ClasificacionI("ROBOT CON LUZ"),
    new ClasificacionI("ROMPECABEZAS"),
    new ClasificacionI("ROSARIO RELIGIOSO"),
    new ClasificacionI("RUBOR ECONOMICO"),
    new ClasificacionI("RUBOR PREMIUM"),
    new ClasificacionI("SACAPUNTAS COSMETICO"),
    new ClasificacionI("SACAPUNTAS ESCOLAR"),
    new ClasificacionI("SALERO"),
    new ClasificacionI("SELLO"),
    new ClasificacionI("SILICA"),
    new ClasificacionI("SLIME JUGUETE"),
    new ClasificacionI("SOMBRA DE OJOS"),
    new ClasificacionI("SOMBRA LIQUIDA"),
    new ClasificacionI("SOMBRA PARA CEJAS"),
    new ClasificacionI("SOMBRILLA PARAGUAS"),
    new ClasificacionI("SONAJA"),
    new ClasificacionI("SOPORTE PARA CELULAR"),
    new ClasificacionI("STICKER DECORATIVO"),
    new ClasificacionI("TENEDOR"),
    new ClasificacionI("TIJERA BIGOTERA ACERO INOXIDABLE"),
    new ClasificacionI("TIJERA BIGOTERA ECONOMICA"),
    new ClasificacionI("TIJERA BIGOTERA PREMIUM"),
    new ClasificacionI("TIJERA CON PEINE"),
    new ClasificacionI("TIJERA CUIDADO PERSONAL ACERO INOXIDABLE"),
    new ClasificacionI("TIJERA CUIDADO PERSONAL ECONOMICA"),
    new ClasificacionI("TIJERA DE COSTURA"),
    new ClasificacionI("TIJERA ESCOLAR"),
    new ClasificacionI("TIJERA ESTILISTA CABALLERO"),
    new ClasificacionI("TIJERA MULTIUSOS"),
    new ClasificacionI("TIJERA PARA CEJAS"),
    new ClasificacionI("TIJERA PLEGABLE"),
    new ClasificacionI("TINTA PARA CEJAS"),
    new ClasificacionI("TIRANTE DE BRASIER"),
    new ClasificacionI("TOALLA DESMAQUILLANTE"),
    new ClasificacionI("TOALLA HUMEDA"),
    new ClasificacionI("TOALLA QUITA ESMALTE"),
    new ClasificacionI("TOPPER"),
    new ClasificacionI("TRAPO"),
    new ClasificacionI("TROMPO"),
    new ClasificacionI("UÑA POSTIZA"),
    new ClasificacionI("VALERINA PARA CABELLO"),
    new ClasificacionI("VASO"),
    new ClasificacionI("VELAS"),
    new ClasificacionI("VOLTEADOR"),
    new ClasificacionI("YOYO")
  ];


  guardarItem(){
    this.andService.crearItem(this.nuevoForm).subscribe(
      (data)=>{
        console.log(data);
        this.limpiar();
      }
    );
  }

  limpiar(){

  }
}
